### ISSUE TITLE
Sources for MCU binaries?

### ISSUE THREAD

**Issue by cyrozap** [OSVR/OSVR-HDK#2]
Will the microcontroller firmware be made open source? It would be nice to have that available so support for other displays could be added.

**Comment by IvanChen0** [comment]
the same question!

**Comment by Oxore** [comment]
Btw, what about Spartan FPGA RTL firmware? Going to build all hardware by myself and can't find FPGA firmware here.

**Comment by heluozhijian** [comment]
The same question: Will the microcontroller firmware be made open source?

**Comment by Kasijjuf** [comment]
Still waiting for the firmware source. Hurry up and release the firmware source code or stop falsely claiming this project is open source.

**Comment by artob** [comment]
Did this ever happen?

**Comment by danuker** [comment]
I'm not buying this hardware, for this very reason.

**Comment by rpavlik** [comment]
It's up to Razer to do this now and keep promises, everything from third
parties was approved as far as I know.

**Comment by MulanVR** [comment]
Ryan, can you make the firmware public? It's in sensics repo. Razer had been also asking (for 2 years now) to make this public...

**Comment by rpavlik** [comment]
Sorry about the miscommunications - the asks hadn't made it down to my level, thought there might still be some approval required. (There might be some weird almost-useless include that I wasn't fully assured of the Apache 2-ness of IIRC, but those should be easy to replace if they exist.)

Have now opened the repo, at last - sorry this took so long, I am quite happy it finally is open though I wish it was earlier too: https://github.com/OSVR/OSVR-HDK-MCU-Firmware

I don't remember what the various non-master branches are - probably in-progress attempts at cleanup or refactoring, since parts of the code were fairly "legacy". However, I had been tagging releases and such in this specific repo for some time, so it should be fairly useful.

**Comment by rpavlik** [comment]
(And of course, @MulanVR , if there are any other Sensics repos that you'd like me to flip the "open-source" switch on [that aren't otherwise restricted by third-party NDAs], just let me know the repos and licenses! :D )

**Comment by ShalokShalom** [comment]
Is there still any plan to release the hardware also?

**Comment by godbyk** [comment]
@ShalokShalom See the https://github.com/OSVR/OSVR-HDK repository.

**Comment by ShalokShalom** [comment]
Thanks. Can you help to clear things up? Wikipedia says, this is not really open source: 
https://en.wikipedia.org/wiki/Open_Source_Virtual_Reality

**Comment by justinclift** [comment]
Interesting question.  Looking at the [License in the GitHub repo](https://github.com/OSVR/OSVR-HDK/blob/master/LICENSE.md), it's clearly **not** Open Source.  Clause 3 includes this:

> ... you may not use, sell or **distribute** the MDK, Modules or Module Interface Technology nor the IPR contained therein for any purposes whatsoever ...

As a data point, clause 8 specifically excludes the source code from that license:

> Any software, namely Source Code or Object Code that is made available on the OSVR Project is excluded from the terms of this License. Such software will be governed by separate terms and conditions set out elsewhere at www.osvr.com.

Not sure what the source code license is, as I didn't see anything obvious when checking the www.osvr.com website quickly.  The license for the non-source-code pieces is very clear though.

**Comment by MulanVR** [comment]
Any OSVR partner is allowed to produce and sell derivative work. The limitations are based on aknowledgement of being in fact derivative, and guidance on "powered by OSVR" logo plus marketing messaging if any. The logo guidance is available on the marketing section.
The goal here as always been to strengthen an open and horizontal ecosystem, which by the way it's entirely free and owned by the community, and allow everybody to accelerate their development to go focus on the hard problems of VR without wasting too much time on reinventing the wheel. 
Go produce something awesome!

**Comment by ShalokShalom** [comment]
> Any OSVR partner is allowed to produce and sell derivative work. The limitations are based on aknowledgement of being in fact derivative, and guidance on "powered by OSVR" logo plus marketing messaging if any. The logo guidance is available on the marketing section.

That would be the case in BSD licences too. Why is OSVR not accepted as an open source license by Github and why is OSVR using an own license in the first place? 

Thy

**Comment by rpavlik** [comment]
It's not really worth it to debate this at this point - it's perhaps not the greatest license but it's only for the hardware part, and open source hardware licensing is still fairly immature in general compared to the situation for software (few permissive, vs copyleft-style, licenses, no overwhelming precedent, and a totally different legal background - copyright not really being as important for a finished product, compared to, e.g. patents), and was even more nebulous when the hardware files were released years ago. It's not really a custom license - it's basically the license for the (ill-fated) Google Project Ara modular smartphone effort. (And as such, is a bit more stringent than you might expect, due to plans to comply with rf regulatory frameworks,etc)

In any case it doesn't affect you if you're using the hardware, or even modifying the firmware: basically everything except the physical bits are Apache 2.0. (the tracking hardware and firmware is Apache2 as well, and the firmware for the headset is now also Apache2...) Even with any perceived flaws in the hardware plans license, the hardware is still more open than the vast majority of other HMDs out there, and these releases played an important part in setting standards and moving the industry forward.

**Comment by ShalokShalom** [comment]
> it's perhaps not the greatest license but it's only for the hardware part

:roll_eyes:
